#!/usr/bin/env python3
# ProsperoEden - Bake the loading screen's lettering into GLSL distance fields.
# Copyright (C) 2026 BlackBearReloaded
# SPDX-License-Identifier: GPL-3.0-or-later
"""Writes headless/loading_text.glsl: capitals, digits and a few signs of Montserrat Medium as
small signed distance fields packed into constant arrays (one per glyph), and the loading screen's lines of text
as indexes into them, so the loading shader needs no texture and no font at run time.

A glyph's field is WIDTH x HEIGHT texels of four bits each (eight per uint, lowest bits first, top
row first): 7.5 on the outline, 15 SPREAD texels inside, 0 SPREAD texels outside. The fields are
kept this small on purpose: a console takes about a millisecond per word to compile them. The glyph stands on
a baseline BASE texels above the field's bottom, LEFT texels from its left edge, with capitals CAP
texels high.
"""

from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).resolve().parents[2]
FONT = ROOT / "third_party/fonts/Montserrat-Medium.ttf"
OUTPUT = ROOT / "headless/loading_text.glsl"

# The lines the screen shows, in the order the shader names them (loading_scene.glsl).
LINES = ["PROSPEROEDEN", "READING THE GAME", "STARTING GRAPHICS", "BUILDING SHADERS", "STARTING THE GAME",
         "LOADING", "S"]
# Only the glyphs the lines use, then the digits and signs of the figures.
GLYPHS = "".join(sorted(set("".join(LINES)) - {" "})) + "0123456789%/"
WIDTH, HEIGHT = 24, 20    # texels of one glyph's field
CAP, BASE, LEFT = 12, 4, 3
SPREAD = 2.0              # texels of distance stored each side of the outline
SCALE = 8                 # a glyph is drawn this much larger, then measured


def draw_glyph(font, letter):
    """The glyph as a boolean mask SCALE times the field's size."""
    image = Image.new("L", (WIDTH * SCALE, HEIGHT * SCALE))
    ImageDraw.Draw(image).text((LEFT * SCALE, (HEIGHT - BASE) * SCALE), letter, font=font, fill=255, anchor="ls")
    mask = np.asarray(image) >= 128
    assert not mask[:, -SCALE:].any() and not mask[:SCALE].any(), f"{letter!r} needs a larger field"
    return mask


def distance_field(mask):
    """Signed distance to the outline in field texels, sampled at texel centres."""
    inside = np.argwhere(mask).astype(np.float32)
    outside = np.argwhere(~mask).astype(np.float32)
    ys = (np.arange(HEIGHT) + 0.5) * SCALE - 0.5
    xs = (np.arange(WIDTH) + 0.5) * SCALE - 0.5
    field = np.zeros((HEIGHT, WIDTH), np.float32)
    # Only pixels within the spread matter; the rest clamp to the ends of the range.
    step = 2  # every second pixel of the mask is near enough for a field this coarse
    inside, outside = inside[::step], outside[::step]
    for row, y in enumerate(ys):
        points = np.stack([np.full(WIDTH, y, np.float32), xs.astype(np.float32)], axis=1)
        to_inside = np.sqrt(((points[:, None, :] - inside[None, :, :]) ** 2).sum(-1)).min(1) if len(inside) else np.full(WIDTH, 1e9)
        to_outside = np.sqrt(((points[:, None, :] - outside[None, :, :]) ** 2).sum(-1)).min(1)
        is_inside = mask[int(round(y)), np.round(xs).astype(int)]
        field[row] = np.where(is_inside, to_outside, -to_inside) / SCALE
    return field


def main():
    font = ImageFont.truetype(str(FONT), round(CAP * SCALE / 0.70))  # Montserrat capitals are 0.70 em
    data, advances = [], []
    for letter in GLYPHS:
        field = distance_field(draw_glyph(font, letter))
        data.append(np.clip(np.round(7.5 + field / SPREAD * 7.5), 0, 15).astype(np.uint32).reshape(-1))
        advances.append(font.getlength(letter) / SCALE)
    # One table per glyph: a console compiles a shader with one large table very slowly (its time grows
    # much faster than the table), and several small ones quickly.
    tables = [sum(d[shift::8] << (4 * shift) for shift in range(8)) for d in data]
    codes, starts = [], []
    for line in LINES:
        starts.append((len(codes), len(line)))
        codes += [GLYPHS.index(letter) if letter != " " else -1 for letter in line]
    lines = [
        "// Generated by tools/launcher/bake-loading-text.py from Montserrat Medium (SIL Open Font",
        "// License 1.1). Do not edit: change the script and run it again.",
        f"const int kGlyphWidth = {WIDTH};",
        f"const int kGlyphHeight = {HEIGHT};",
        f"const float kGlyphCap = {CAP:.1f};",
        f"const float kGlyphBase = {BASE:.1f};",
        f"const float kGlyphLeft = {LEFT:.1f};",
        f"const float kGlyphSpread = {SPREAD:.1f};",
        f"const int kDigit = {GLYPHS.index('0')};",
        f"const int kPercent = {GLYPHS.index('%')};",
        f"const int kSlash = {GLYPHS.index('/')};",
        "// How far each glyph moves the pen, in texels.",
        f"const float kAdvance[{len(advances)}] = float[{len(advances)}](",
        "    " + ", ".join(f"{value:.2f}" for value in advances) + ");",
        "// The lines of text: glyph indexes (-1 is a space), and where each line starts and how long it is.",
        f"const int kText[{len(codes)}] = int[{len(codes)}](",
        "    " + ", ".join(str(code) for code in codes) + ");",
        f"const ivec2 kLine[{len(starts)}] = ivec2[{len(starts)}](",
        "    " + ", ".join(f"ivec2({start}, {count})" for start, count in starts) + ");",
    ]
    for index, words in enumerate(tables):
        lines.append(f"const uint kGlyph{index}[{words.size}] = uint[{words.size}](")
        for start in range(0, words.size, 8):
            chunk = ", ".join(f"0x{value:08x}u" for value in words[start:start + 8])
            lines.append("    " + chunk + ("," if start + 8 < words.size else ""))
        lines.append(");")
    lines += ["// One word of a glyph's field.", "uint glyph_word(int glyph, int word)", "{", "    switch (glyph)", "    {"]
    lines += [f"    case {index}: return kGlyph{index}[word];" for index in range(len(tables))]
    lines += ["    }", "    return 0u;", "}"]
    words = np.concatenate(tables)
    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"{OUTPUT.name}: {len(GLYPHS)} glyphs of {WIDTH}x{HEIGHT} texels, {words.size} words, {len(LINES)} lines")


if __name__ == "__main__":
    main()
